services:
  web:
    build: .
    ports:
      - "${HOST_IP:-0.0.0.0}:8080:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db

  db:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=caching_sha2_password
      --authentication-policy=caching_sha2_password
      --host-cache-size=0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - TZ=UTC
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
