services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./htdocs:/var/www/html/
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env

  db:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=caching_sha2_password
      --authentication-policy=caching_sha2_password
      --host-cache-size=0
    restart: always
    env_file:
      - .env
    
    environment:
      - TZ=UTC
      
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
