<?php

// REDIRECT EXTERNAL HITS TO INFO PAGE

$gallery_ip = "203.14.59";
$local_ip = "203.45";
$client_ip = getIP();
$redir = ""; //No redirect
$info_page = "/surfacebrowser_info.html";


function getIP()
{
  $ip = "";
  if (getenv("HTTP_CLIENT_IP")) $ip = getenv("HTTP_CLIENT_IP");
  else if (getenv("HTTP_X_FORWARDED_FOR")) $ip = getenv("HTTP_X_FORWARDED_FOR");
  else if (getenv("REMOTE_ADDR")) $ip = getenv("REMOTE_ADDR");
  else $ip = "UNKNOWN";
  return $ip;
}

// Step 1. Just disabling form for external hits and linking to info page.

// Step 2.
// redirect if direct hit and not from ZKM or (me). direct hit = (referrer != infopage)
// if referred by info page (ie. hit from external site), disable form in head
//$refMask = strpos($HTTP_REFERER, $info_page);

//if ($refMask === FALSE && strpos($client_ip,$gallery_ip)!==0 && strpos($client_ip,$local_ip)!==0)
//{
// $redir = "Location: http://" . $_SERVER['HTTP_HOST'] . $info_page;
// header($redir);
// exit;
//}

//


?>
<html>

<head>
  <title>Surface Browser</title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <!--<?php echo "Mask: " . "$gallery_ip" . "," . "$local_ip" . " Client: " . "$client_ip" . " => " . "$redir"; ?>-->
</head>

<frameset rows="201,190,*" framespacing="0" frameborder="no" border="0">
  <frame src="head.phtml" name="sb_head" marginwidth="4" marginheight="5" scrolling="NO" noresize />
  <frameset cols="326,*" framespacing="0" frameborder="no" border="0">
    <frame src="side.html" name="sb_side" marginwidth="4" marginheight="8" scrolling="NO" />
    <frame src="post.phtml" name="sb_links" marginwidth="0" marginheight="8" />
  </frameset>
  <frame src="surfacebrowser_instruction.html" name="sb_content" marginwidth="4" marginheight="2" />
</frameset>
<noframes>

  <body leftmargin="0" topmargin="0" marginwidth="0" bgcolor="#FFFFFF">
    Refer <a href="http://www.boxc.net/surfacebrowser_info.html">http://www.boxc.net/surfacebrowser_info.html</a>
  </body>
</noframes>

</html>