<?php
require_once 'config.php';
require_once 'db_functions.php';
require_once 'link_functions.php';

set_headers();

$db = connectToDatabase();
$link_test = filter_input(INPUT_GET, 't', FILTER_SANITIZE_NUMBER_INT);

?>
<html>

<body>
    <?php
    if ($link_test != 1) {
        $link = getNextLink($db, SB_DATA_TABLE);
        // log link
        error_log("Link: " . json_encode($link));
        if ($link) {
            switch($link['type']) {
                case TYPE_URL:
                    $iconImg = "images/sb_url.gif";
                    break;
                case TYPE_AI:
                    $iconImg = "images/sb_ai.png";
                    break;
                default:
                    $iconImg = "images/sb_img.gif";
            }
            echo "<a href=\"" . htmlspecialchars($link['url']) . "\"><img src=\"" . 
                $iconImg . "\" alt=\"Link icon\"></a>";
        } else {
            echo "No links available.";
        }
    } else {
        $hasActiveLinks = checkActiveLinks($db, SB_DATA_TABLE);
        if ($hasActiveLinks) {
            echo "<img src=\"images/sb_img.gif\" alt=\"Active links\">";
        } else {
            echo "None new.";
        }
    }
    ?>
</body>

</html>