<?php require_once 'config.php'; require_once 'init.php'; ?>
<?php
$img = strip_tags($_GET["b_img"]);
?>
<!DOCTYPE html>
<html lang="<?php echo $_SESSION['lang']; ?>">
<head>
  <style type="text/css">
    <!--
    body {
      font-family: Arial, Helvetica, sans-serif;
      font-size: 12px
    }
    -->
    <meta charset="UTF-8">
    <title><?php echo t('page_title'); ?></title>
</head>
<body bgcolor="#FFFFFF">
  <p>
    <font face="Verdana, Arial, Helvetica, sans-serif" size="2"><a href="surfacebrowser_info.html">back</a></font>
  </p>
  <p><img src="../../media/<?php echo "$img" ?>.jpg"></p>
</body>

</html>