<html>

<head>
  <title>Surface Browser :: Tim Plaisted</title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <script language="JavaScript">
    <!--
    // Disable right mouse button. from Doc Javascript
    function click() {
      if (event.button == 2) {
        alert("gallery block");
      }
    }
    document.onmousedown = click

    //
    -->
  </script>
  <style type="text/css">
    <!--
    body {
      font-family: Arial, Helvetica, sans-serif;
      font-size: 12px
    }
    -->
    <?php
    $img = strip_tags($_GET["b_img"]);
    ?>
  </style>
</head>

<body bgcolor="#FFFFFF">
  <p>
    <font face="Verdana, Arial, Helvetica, sans-serif" size="2"><a href="surfacebrowser_info.html">back</a></font>
  </p>
  <p><img src="../../media/<?php echo "$img" ?>.jpg"></p>
</body>

</html>